### ISSUE TITLE
Scrape More Research Contribution Data

### ISSUE THREAD

**Issue by kakka0903** [search-rug/search-rug.github.io#28]
## Context 

The research page presents us with research contributions by the SEARCH group. This data is scraped from RSS feeds on `research.rug.nl` by a python script that is ran weekly by GitHub actions. Currently the script collects two types of research contributions: publications and datasets. For each type the `title` and `url` is collected. On the website each contribution is rendered by the `research-contribution-card` component. 

## Scraping more data

As of now the presentation of the research contributions is very basic. Only the title is displayed, which when clicked takes the user to the corresponding `research.rug.nl` page. This gives little value to the user, and requires a lot of navigation to third-party pages to view more details. The contribution component can display both a description and a download count, so if this data could be scraped as well, then the contributions sections can be more complete.  

There are some challenges to overcome in regards to rendering the RSS description HTML, and to obtain download count data. The description data from the RSS feeds are formatted as escaped html, so to display it in the DOM the descriptions need to be un-escaped to be properly rendered. Furthermore, the download counts displayed on `research.rug.nl` are not present in the RSS data, so an alternative way needs to be conceived to obtain that data.

## Relevant links

Here are some relevant links:

- [contributions.py script](https://github.com/search-rug/search-rug.github.io/blob/6496e4223cc35085aace5e186ddaedc692aba0d9/scripts/contributions.py)
- [research.rug.nl](https://research.rug.nl/en/organisations/software-engineering/datasets/)
- [RSS example](https://github.com/search-rug/search-rug.github.io/files/11365110/zqlw2ium.txt)
- [research contributions github workflow](https://github.com/search-rug/search-rug.github.io/blob/6496e4223cc35085aace5e186ddaedc692aba0d9/.github/workflows/update-research-contributions.yml)

**Comment by feitosa-daniel** [comment]
Update:
- commit 47eee35a69e62b87f7c9d1e5a2bb85249d2863b8 adds support for extracting and parsing descriptions.
- commit 90824544e3c1f9735fd7d68c1fb4a8920e7ce663 updates the card to use the parsed description.

**Comment by feitosa-daniel** [comment]
Extracting any more relevant information (e.g., DOI) would involve more scraping or call to publication search APIs. The effort and added complexity (i.e., more room for bugs later on) does not justify the diminishing results at the moment. And we now clarify that we only show recent publications (53d9c3771b7d3875b703bc3c90a59ca32aa49a88), and point to Pure (which incl. all details). Closing this issue for now.
